LOGIN = ENV.fetch("LOGIN", "mehdi")
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"

Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.vm.box = ENV.fetch("BOX", "ubuntu/jammy64")
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "#{LOGIN}S" do |srv|
    srv.vm.hostname = "#{LOGIN}S"
    srv.vm.network "private_network", ip: SERVER_IP
    srv.vm.provider "virtualbox" do |vb|
      vb.name = "#{LOGIN}S"
      vb.cpus = 1
      vb.memory = 1024
    end
    srv.vm.provision "shell", path: "scripts/install_k3s_server.sh", args: [SERVER_IP, LOGIN], env: { "K3S_TOKEN" => "IOTSUPERSECRETTOKEN123" }
  end

  config.vm.define "#{LOGIN}SW" do |agt|
    agt.vm.hostname = "#{LOGIN}SW"
    agt.vm.network "private_network", ip: WORKER_IP
    agt.vm.provider "virtualbox" do |vb|
      vb.name = "#{LOGIN}SW"
      vb.cpus = 1
      vb.memory = 1024
    end
    agt.vm.provision "shell", path: "scripts/install_k3s_agent.sh", args: [SERVER_IP, WORKER_IP, LOGIN], env: { "K3S_TOKEN" => "IOTSUPERSECRETTOKEN123" }
  end
end
